version: "2"
services:
  # Elasticsearch
  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    restart: ${RESTART_POLICY}
    volumes:
      - ${PROJECT_PATH}/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ${PROJECT_PATH}/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ES_JAVA_OPTS
      - TAKE_FILE_OWNERSHIP=1
  kibana:
    image: kibana:${KIBANA_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - SERVER_BASEPATH=/kibana
      # - XPACK_SECURITY_ENABLED=true
      # - ELASTICSEARCH_USERNAME=kibana_system
      # - ELASTICSEARCH_PASSWORD=${KIBANA_ES_PASSWORD}
    depends_on:
      - elasticsearch 
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        PYTHON_DOCKER_VERSION: ${PYTHON_DOCKER_VERSION}
    restart: ${RESTART_POLICY}
    depends_on:
      - elasticsearch
    volumes:
      - ${PROJECT_PATH}/api:/api
      - ${PROJECT_PATH}/data:/data
    environment:
      - MODE=${MODE}
